### ISSUE TITLE
link to code is broken

### ISSUE THREAD

**Issue by sbelharbi** [XinshaoAmosWang/Improving-Mean-Absolute-Error-against-CCE#2]
hi,
the provided link to the code seems to be broken https://www.dropbox.com/sh/vb48gq7rugeugtm/AAACFbUSqAc8XNmVr_PniUena?dl=0 . 
can you provide a valid link? thanks

**Comment by XinshaoAmosWang** [comment]
Many thanks for your interest. 

https://xinshaoamoswang.github.io/blogs/2020-06-14-code-releasing/

**Comment by sbelharbi** [comment]
thanks
