### ISSUE TITLE
link to code is broken again

### ISSUE THREAD

**Issue by sailist** [XinshaoAmosWang/Improving-Mean-Absolute-Error-against-CCE#3]
hi,
the provided link to the code seems to be broken again
https://www.dropbox.com/sh/pmrnh4kdrxbisbj/AACtxvIOc7AoO9xLeySfHvgLa?dl=0
in https://xinshaoamoswang.github.io/my_docs/IMAE_Code_Illustration
can you renew this link? thanks :)

**Comment by XinshaoAmosWang** [comment]
@sailist 
Please contact me personally using email if you have any question. Thanks.

**Comment by sailist** [comment]
Thanks :)
